### ISSUE TITLE
Set up basic socket connection for projects

### ISSUE THREAD

**Issue by sanderaido** [learning-layers/timeliner#50]
Using Socket.io "rooms" for each project 
#49

**Comment by pjotrsavitski** [comment]
This should also have a notion of authentication within it as a certain room (for a project) could only be joined by its members.

Socket.io should have that kind of possibility available. The connection would be refused otherwise.

**Comment by pjotrsavitski** [comment]
Done, specific implementation extensions will be part of targeted issues.
