### ISSUE TITLE
Project view

### ISSUE THREAD

**Issue by vtomberg** [learning-layers/timeliner#54]
To start with creation, modifying and deleting of:

- Annotations
- Milestones

**Comment by pjotrsavitski** [comment]
Current initial view has an element for doing that (FAB button).

This might be a viable solution but one that would require a user to select certain date-time value (could be pre-filled with today).

Another solution would be to allow clicking on certain **Group lane** (a special track on the timeline) that would show a dialog with data inputs for newly created Annotation or Milestone. This way data-time would be determined by the place clicked. Later on it would be possible to change that by dragging the element elsewhere.

The resulting solution could even be a hybrid approach both allowing a click on the timeline group space with preselected date-time and creation from within the menu. The latter one would have the date-time element choice with today being set by default.

**Comment by pjotrsavitski** [comment]
I would say that we should close this one, even if some of the attached issues are still in active.
New and better targeted issues should be created instead. The project view is already there and it has a lot more functionality than this one describes.
