### ISSUE TITLE
Stacking of items on timeline

### ISSUE THREAD

**Issue by sanderaido** [learning-layers/timeliner#66]
Should we use vis.js's stacking feature for items or disable it and force just each task on it's own subgroup? This would mean that each task is on its own row inside the tasks group, but only when it's actually in the visible part of the timeline (not somewhere in the future or past). But this would also benefit by not stacking simple items like annotations and milestones (this is especially visible when zooming far out on the timeline)
I have attached a few sample images from before (with stacking) and after (no stacking with subgroup for each task).

### Regular zoom
Before
![screen shot 2016-09-16 at 12 53 29](https://cloud.githubusercontent.com/assets/9868517/18582821/b3c17f88-7c0f-11e6-95f9-be1441a4ccf9.png)
After
![screen shot 2016-09-16 at 12 54 16](https://cloud.githubusercontent.com/assets/9868517/18582826/c11a7a04-7c0f-11e6-9695-ae8f8df3d9bd.png)

### Zoomed very out (maybe you have a long project)
Before
![screen shot 2016-09-16 at 12 55 24](https://cloud.githubusercontent.com/assets/9868517/18582871/f10d179e-7c0f-11e6-942d-036a397866f0.png)
After
![screen shot 2016-09-16 at 12 54 34](https://cloud.githubusercontent.com/assets/9868517/18582873/f6209df0-7c0f-11e6-9811-fde05506ccc1.png)

### Zoomed very in (both cases are quite similar, all tasks which are out of range also lose their designated row)
Before & after look still the same
![screen shot 2016-09-16 at 13 12 10](https://cloud.githubusercontent.com/assets/9868517/18582902/1c353096-7c10-11e6-92e1-98637edd3513.png)

**Comment by pjotrsavitski** [comment]
I suppose that current change will remain in as it is, if tunes and changes are needed, then these will be implemented as needed.
